name: 'NPM Cache and INstalling Dependency'
description: 'Using as a Composite action'
inputs:
  path-of-folder:  # id of input
    description: 'folder location'
    required: true
runs:
  using: "composite"
  steps:
    - name: Saving Cache 
      uses: actions/cache@v4
      with:
        path: ${{ inputs.path-of-folder }}
        key: ${{ runner.os }}-node-modules-${{ hashFiles('package-lock.json') }}

    - name: Install Dependencies
      run: npm install 
      shell: bash