name: solar system

on: 
  workflow_dispatch: 
  push: 
    branches: 
    - main
    - feature/* 

jobs: 
  unit-testing: 
    name: unit testing
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Setup NodeJS Actions
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Install Dependencies
        run: npm install 

      - name: Unit Testing
        run: npm test 