name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{vars.MONGO_URI}}
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [20, 18, 19]
            operating-system: [ubuntu-latest, macos-latest]
            exclude:
              - node-version: 18
                operating-system: macos-latest
            
        runs-on: ${{ matrix.operating-system }}
        steps:

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version -${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}
    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result${{matrix.node-version}}-${{ matrix.operating-system }}
            path: test-results.xml
            retention-days: 5  #store the artifact for 5 days

    code-coverage:
          name: code coverage
          runs-on: ubuntu-latest
          needs: unit-testing
          
          steps:

          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup NodeJS Version 
            uses: actions/setup-node@v3
            with:
              node-version: 18
      
          - name: Install Dependencies
            run: npm install
      
          - name: Unit Testing
            run: npm run coverage
            
          - name: Archive Test Result
            if: failure()  # Archive the test result only if the test fails 
            uses: actions/upload-artifact@v4
            with:
              name: code coverage results
              path: coverage
              retention-days: 5  #store the artifact for 5 days 