name: Deploy to AWS Lambda

on:
  workflow_dispatch:
  push:
    branches: 
        - feature/practice
  pull_request:
    branches: 
        - feature/practice

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        

    - name: Install dependencies
      run: |
        # For Node.js
        npm ci
        
        # For Python
        # pip install -r requirements.txt

    - name: Zip Function Code
      run: |
        # Create deployment package
        zip -r function.zip . -x "*.git*" "node_modules/*" "tests/*" "*.md"
        # If using Node.js with included node_modules, use:
        # zip -r function.zip . -x "*.git*" "tests/*" "*.md"

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://function.zip
        
     