name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: mongodb+srv://yagen1111:REY9u59pG50bVTuq@cluster0.uw8v3gr.mongodb.net/superData
  MONGO_USERNAME: yagen1111
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    
    unit-testing:
        name: Unit Testing
        services:
          mongo-db:
            image: siddharth67/mongo-db:non-prod
            ports:
              - 27017:27017
            env:
                MONGO_URI: mongodb://localhost:27017/superData
                MONGO_USERNAME: non-prod-user
                MONGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version
          uses: actions/setup-node@v3
          with:
            node-version: 20
        - name: Cache Node Modules
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules${{ hashFiles('package-lock.json') }} 

    
        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          id: nodejs-unit-test-step
          run: npm test
          
          
        - name: Archive Test Result
          if: always()
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result
            path: test-results.xml
    code-coverage:


     needs: unit-testing
     name: Code Coverage
     container:
        image: node:18
     services:
      mongo-db:
        image: siddharth67/mongo-db:non-prod
        options: 
          --name mongo
        env:
            MONGO_URI: mongodb://mongo:27017/superData
            MONGO_USERNAME: non-prod-user
            MONGO_PASSWORD: non-prod-password

     runs-on: ubuntu-latest
     steps:
     - name: Checkout Repository
       uses: actions/checkout@v4

     - name: Install Dependencies
       run: npm install
     - name: Cache Node Modules
       uses: actions/cache@v4
       with:
        path: node_modules
        key: ${{ runner.os }}-node-modules${{ hashFiles('package-lock.json') }} 

    
     - name: Run Code Coverage
       continue-on-error: true
       run: npm run coverage


     - name: Upload Code Coverage Report
       uses: actions/upload-artifact@v4
       with:
         name: Code-Coverage-Report
         path: coverage
         retention-days: 5
    docker:
      needs: [unit-testing, code-coverage]
      name: Docker Build and Push
      runs-on: ubuntu-latest
      steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
  
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: GHCR Login 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
  
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}

      - name: image test
        run: |
          docker images
          docker run --name solar-system-test -d \
           -p 3000:3000 \
           -e MONGO_URI=$MONGO_URI\
           -e MONGO_USERNAME=$MONGO_USERNAME\
           -e MONGO_PASSWORD=$MONGO_PASSWORD \
           ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
          export ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-test)
          echo "IP Address: $ip"

          echo "Waiting for the application to start..."
          wget -q -O - 127.0.0.1:3000/live | grep live

      - name: crp
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
                ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
                ghcr.io/${{ github.repository_owner }}/solar-system:${{ github.sha }}
    
    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Set up Kubernetes cluster with Kind
          uses: helm/kind-action@v1.8.0
      
        - name: check up Kubeconfig
          run:  kubectl get nodes

        - name: Install ingress-nginx (for kind)
          run: |
            kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.9.6/deploy/static/provider/kind/deploy.yaml

        - name: Wait for ingress-nginx controller to be ready
          run: |
            kubectl wait --namespace ingress-nginx \
            --for=condition=Ready pod \
            --selector=app.kubernetes.io/component=controller \
            --timeout=180s

        - name: Get Ingress NodePort and expose as INGRESS_URL
          run: |
            NODE_PORT=$(kubectl get svc ingress-nginx-controller \
            -n ingress-nginx \
            -o jsonpath="{.spec.ports[?(@.port==80)].nodePort}")
            echo "INGRESS_URL=http://localhost:$NODE_PORT" >> $GITHUB_ENV
            echo "Ingress available at http://localhost:$NODE_PORT"

        # - name: Get ingress IP
        #   run: |
        #     echo "INGRESS_IP=$(kubectl get svc -n default ingress-nginx-controller -o jsonpath="{.status.loadBalancer.ingress[0].ip}")" >> $GITHUB_ENV
        

        - name: replace
          uses: cschleiden/replace-tokens@v1
          with:
            tokenPrefix: '_{_'
            tokenSuffix: '_}_'
            files: '["kubernetes\development*.yaml"]'
          env:
            NAMESPACE: ${{ vars.NAMESPACE }}
            REPLICAS: ${{ vars.REPLICAS }}
            IMAGE: ${{ secrets.DOCKER_USERNAME }}/solar-system:${{ github.sha }}
            INGRESS_IP: ${{ env.INGRESS_IP }}

        - name: create mongo secret
          run: |
            kubectl -n ${{vars.NAMESPACE }} create secret generic mongo-db-creds \
              --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
              --from-literal=MONGO_USERNAME=${{env.MONGO_USERNAME }} \
              --from-literal=MONGO_PASSWORD=${{secrets.MONGO_PASSWORD }} \
              --save-config \
              --dry-run=client -o yaml | kubectl apply -f -
        - name: deploy files
          run: |
            kubectl apply -f kubernetes/development
 