name: Solar Systems Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_URI: mongodb+srv://${{vars.MONGO_USERNAME}}:${{secrets.MONGO_PASSWORD}}@cluster0.h87iivl.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup NodeJS Version - 18
        uses: actions/setup-node@v5
        with: 
          node-version: 18
      - name: Install all Dependencies
        run: npm install
      
      - name: Unit Testing
        run: npm test


