name: Solar System Workflow

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_URI: ${{vars.MONGO_URI}}
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  
jobs:
    unit-testing:
        name: Unit Testing
        strategy:
          matrix:
            node-version: [20, 18, 19]
            operating-system: [ubuntu-latest]
            exclude:
              - node-version: 18
                operating-system: macos-latest
            
        runs-on: ${{ matrix.operating-system }}
        steps:

        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup NodeJS Version -${{ matrix.node-version }}
          uses: actions/setup-node@v3
          with:
            node-version: ${{ matrix.node-version }}

        - name: chaching the dependencies
          uses: actions/cache@v4
          with:
            path: node_modules
            key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

        - name: Install Dependencies
          run: npm install
    
        - name: Unit Testing
          run: npm test
          
        - name: Archive Test Result
          uses: actions/upload-artifact@v4
          with:
            name: Mocha-Test-Result${{matrix.node-version}}-${{ matrix.operating-system }}
            path: test-results.xml
            retention-days: 5  #store the artifact for 5 days

    code-coverage:
          name: code coverage
          runs-on: ubuntu-latest
          
          steps:

          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Setup NodeJS Version 
            uses: actions/setup-node@v3
            with:
              node-version: 18
          
          - name: chaching the dependencies
            uses: actions/cache@v4
            with:
              path: node_modules
              key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}

          - name: Install Dependencies
            run: npm install
      
          - name: Unit Testing
            continue-on-error: true
            run: npm run coverage

            
          - name: Archive Test Result
            uses: actions/upload-artifact@v4
            with:
              name: code coverage results
              path: coverage
              retention-days: 5  #store the artifact for 5 days 


    docker:
      name: Docker Build and Push
      runs-on: ubuntu-latest
      needs: [unit-testing, code-coverage]
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: docker login
          uses: docker/login-action@v2
          with:
            username: ${{ vars.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
        - name: dhcr login
          uses: docker/login-action@v2
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: false
            tags: ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

        - name: test docker image
          run: |
            docker images 
            docker run -d --name solar-system -p 3000:3000 \
            -e MONGO_URI=$MONGO_URI \
            -e MONGO_USERNAME=$MONGO_USERNAME \
            -e MONGO_PASSWORD=$MONGO_PASSWORD \
            ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}

            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system)
            echo "IP: $IP"

            echo "testing image using wget"
            wget -q -O - 127.0.0.1:3000/live | grep live 

        - name: push Docker Image
          uses: docker/build-push-action@v4
          with:
            context: .
            file: Dockerfile
            push: true
            tags: |
              ${{ vars.DOCKERHUB_USERNAME }}/solar-system:${{ github.sha }}
              ghcr.io/${{ github.actor }}/solar-system:${{ github.sha }}
            
            