name: solar system

on: 
  workflow_dispatch: 
  push: 
    branches: 
    - main
    - feature/* 

env: 
  MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

jobs: 
  unit-testing: 
    strategy:
      matrix: 
        nodejs_version: [18, 20]
        os: [ubuntu-latest, macos-latest]
        exclude: 
          - nodejs_version: 18
            os: macos-latest  

    name: unit testing
    runs-on: ${{ matrix.os }}
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup NodeJS Actions Version is ${{ matrix.nodejs_version }}
        uses: actions/setup-node@v3
        with: 
          node-version: ${{ matrix.nodejs_version }}

      - name: Install Dependencies
        run: npm install 

      - name: Unit Testing
        id: nodejs-unit-testing
        run: npm test 

      - name: Saving The Result of unit Testing
        if: steps.nodejs-unit-testing.outcome == 'failure' || steps.nodejs-unit-testing.outcome == 'success'
        uses: actions/upload-artifact@v4
        with: 
          name: Mocha-test-results
          #name: Numberwise- ${{ matrix.nodejs_version }} on ${{ matrix.os }}
          path: test-results.xml

  code-coverage: 
    name: Code Coverage
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Actions
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v3
        with: 
          node-version: 18

      - name: Installing Dependencies 
        run: npm install

      - name: Running Code Coverage
        continue-on-error: true
        run: npm run coverage

      - name: Saving the artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Coverage Result
          path: coverage
          retention-days: 1