name: Solar Systems Workflow
on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'
env:
  MONGO_USERNAME: ${{vars.MONGO_USERNAME}}
  MONGO_PASSWORD: ${{secrets.MONGO_PASSWORD}}
  MONGO_URI: mongodb+srv://${{vars.MONGO_USERNAME}}:${{secrets.MONGO_PASSWORD}}@cluster0.h87iivl.mongodb.net/solar_system?retryWrites=true&w=majority&appName=Cluster0
jobs:
  unit-testing:
    strategy:
      matrix:
        nodejs_version: [18, 19, 20]
        operating_system: [ubuntu-latest, macos-latest]
        exlude:
          - nodejs_version: 18
            operating_system: macos-latest

    name: Unit Testing
    runs-on: ${{matrix.operating_system}}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
      
      - name: Setup NodeJS Version - ${{matrix.nodejs_version}}
        uses: actions/setup-node@v5
        with: 
          node-version: ${{matrix.nodejs_version}}
      - name: Install all Dependencies
        run: npm install
      
      - name: Unit Testing
        run: npm test 
      - name: Archive Test Result
        uses: actions/upload-artifact@v4
        with:
          name: Mocha-Test-Result-${{ github.job }}-${{ github.run_number }}
          path: test-results.xml


